// Browser integration tests use a clearly synthetic fixture, not historical data.
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),checks=[];const check=(n,v)=>{assert.ok(v,n);checks.push(n);};
const fixture={year:-770,yearCode:'BC770',territories:[{oid:'TEST-ONLY-1',name:'测试区域',labelCoord:[111,34],areaDeg2:1,rings:[[[[110,33],[112,33],[112,35],[110,35],[110,33]]]]},{oid:'TEST-ONLY-2',name:null,labelCoord:null,areaDeg2:1,rings:[[[[113,33],[115,33],[115,35],[113,35],[113,33]]]]}]};
(async()=>{let browser,server;try{
 server=http.createServer((req,res)=>{const relative=new URL(req.url,'http://localhost').pathname;const f=path.resolve(root,'.'+(relative==='/'?'/index.html':relative));if(!f.startsWith(root+path.sep)||relative==='/data/territories.json'||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end('not found');return;}res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':'text/html');res.end(fs.readFileSync(f));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1512,height:982}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.body.dataset.ready==='awaiting-file');check('empty site offers local import',await page.locator('#chooseSource').isVisible());
 const raw=JSON.stringify(fixture);await page.locator('#fileInput').setInputFiles({name:'test-fixture.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.waitForFunction(()=>document.getElementById('storageStatus').textContent.includes('已保存在本机'));check('input and null count',await page.locator('#total').innerText()==='2'&&await page.locator('#unknown').innerText()==='1');
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');check('cached source restored after real reload',(await page.locator('#storageStatus').innerText()).includes('本机保存'));await page.locator('[data-filter=unknown]').click();check('unknown filter',await page.locator('#regionList .region').count()===1);await page.locator('#regionList .region').click();check('white land not error',(await page.locator('#detail').innerText()).includes('正常白地'));
 await page.locator('#mode').selectOption('outline');check('raw outline layer',await page.evaluate(()=>__atlas.state.mode)==='outline');check('no desktop overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#about').click();await page.locator('#dialogBody button').click();await page.waitForTimeout(200);await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='awaiting-file');check('explicit cache clear survives reload',await page.locator('#chooseSource').isVisible());
 await page.locator('#fileInput').setInputFiles({name:'wrong-year.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...fixture,year:2017}))});await page.waitForFunction(()=>document.getElementById('loadMessage').textContent.includes('前770年'));check('rejects modern date',await page.locator('#loader').isVisible());
 await page.setViewportSize({width:390,height:844});await page.locator('#fileInput').setInputFiles({name:'test-fixture.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.waitForFunction(()=>document.body.dataset.ready==='true');check('no mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#mobileList').click();await page.locator('#regionList .region').first().click();check('mobile detail sheet usable',await page.locator('#detailPanel').isVisible());check('no JS exceptions',errors.length===0);
 const report={status:'PASS',checks_passed:checks.length,checks,data:'synthetic two-object fixture; not a historical map',origin:'local HTTP server; real file picker and IndexedDB'};fs.writeFileSync(path.join(__dirname,'browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
