const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const M=require('../web/data.js');
const fixture=()=>({year:-770,yearCode:'BC770',territories:[{oid:'test:1',name:'测试区域',labelCoord:[111,34],areaDeg2:1,rings:[[[[110,33],[112,33],[112,35],[110,35],[110,33]]]]},{oid:'test:2',name:null,labelCoord:null,areaDeg2:1,rings:[[[[113,33],[115,33],[115,35],[113,35],[113,33]]]]}]});
test('accept BCE770 without inventing fields',()=>{const s=fixture(),before=JSON.stringify(s);const r=M.validate(s);assert.equal(JSON.stringify(s),before);assert.equal(r.source,s);});
test('unknown name is normal',()=>{const r=M.validate(fixture());assert.equal(r.counts.unknown,1);assert.equal(r.whiteLandIsError,false);});
test('uncovered land is not filled',()=>{const r=M.validate(fixture());assert.equal(r.source.territories.length,2);});
test('wrong era rejected',()=>{const x=fixture();x.year=2017;assert.throws(()=>M.validate(x));});
test('wrong year code rejected',()=>{const x=fixture();x.yearCode='AD770';assert.throws(()=>M.validate(x));});
test('duplicate OID rejected',()=>{const x=fixture();x.territories[1].oid=x.territories[0].oid;assert.throws(()=>M.validate(x));});
test('equal labels keep separate IDs',()=>{const x=fixture();x.territories[1].name=x.territories[0].name;assert.equal(M.validate(x).counts.total,2);});
test('missing geometry rejected',()=>{const x=fixture();delete x.territories[0].rings;assert.throws(()=>M.validate(x));});
test('malformed label rejected',()=>{const x=fixture();x.territories[0].labelCoord=[NaN,35];assert.throws(()=>M.validate(x));});
test('nonfinite vertex rejected',()=>{const x=fixture();x.territories[0].rings[0][0][1][0]=Infinity;assert.throws(()=>M.validate(x));});
test('invalid longitude rejected',()=>{const x=fixture();x.territories[0].rings[0][0][1][0]=200;assert.throws(()=>M.validate(x));});
test('open ring rejected rather than repaired',()=>{const x=fixture();x.territories[0].rings[0][0].pop();assert.throws(()=>M.validate(x));});
test('empty feature list rejected',()=>assert.throws(()=>M.validate({year:-770,territories:[]})));
test('name-only index not treated as geometry',()=>assert.throws(()=>M.validate({year:-770,territoryIndex:[]})));
test('GeoJSON adapter keeps coordinates and null',()=>{const c=fixture().territories[1].rings,g={type:'FeatureCollection',metadata:{year:-770},features:[{properties:{oid:'test:2',name:null,year:-770,label_lon:null,label_lat:null,area_deg2:1},geometry:{type:'MultiPolygon',coordinates:c}}]};const r=M.validate(g);assert.strictEqual(r.source.territories[0].rings,c);assert.equal(r.source.territories[0].name,null);});
test('GeoJSON per-feature year checked',()=>{const g={type:'FeatureCollection',metadata:{year:-770},features:[{properties:{year:2017},geometry:{type:'Polygon',coordinates:[]}}]};assert.throws(()=>M.validate(g));});
test('point counts and geographic bounds',()=>{const r=M.validate(fixture());assert.equal(r.counts.points,10);assert.deepEqual(r.bounds,[110,33,115,35]);});
test('runtime does not fetch legacy counties or routes',()=>{const js=fs.readFileSync(path.join(__dirname,'../web/atlas.js'),'utf8');assert.ok(!js.includes('counties.json'));assert.ok(!js.includes('connections.json'));});
const real=path.join(__dirname,'../data/territories.json');if(fs.existsSync(real))test('complete delivered source has 276 records and 131806 vertices',()=>{const r=M.validate(JSON.parse(fs.readFileSync(real,'utf8')));assert.deepEqual(r.counts,{total:276,named:269,unknown:7,points:131806});});
