'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const M = require('../web/model.js');
const root = path.resolve(__dirname, '..');
const counties = JSON.parse(fs.readFileSync(path.join(root, 'data/counties.json')));
const edges = JSON.parse(fs.readFileSync(path.join(root, 'data/connections.json')));
const model = M.create(counties, edges);
const tiny = () => counties.slice(0, 3).map((c, i) => ({ ...structuredClone(c), '县编号': ['A', 'B', 'C'][i] }));
const edge = (a, b, land = null, type = null, ab = null, ba = null) => ({ [M.F.a]: a, [M.F.b]: b, [M.F.land]: land, [M.F.type]: type, [M.F.ab]: ab, [M.F.ba]: ba });
const signature = x => crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');

test('Actual two-table data passes browser contract validation', () => assert.equal(M.validate(counties, edges), true));
test('Seven land classes and exact resource enum', () => { assert.equal(M.LAND.length, 7); assert.equal(M.RESOURCES.length, 9); });
test('No channels represented by zero', () => assert.throws(() => M.create(tiny(), [edge('A', 'B', 0, '能走车')])));
test('Water zero is invalid too', () => assert.throws(() => M.create(tiny(), [edge('A', 'B', null, null, 0)])));
test('Undefined is not null', () => { const e = edge('A', 'B', 1, '能走车'); delete e[M.F.ab]; assert.throws(() => M.create(tiny(), [e])); });
test('NaN cannot be a distance', () => assert.throws(() => M.create(tiny(), [edge('A', 'B', NaN, '能走车')])));
test('Empty county pairs rejected', () => assert.throws(() => M.create(tiny(), [edge('A', 'B')])));
test('Land without type rejected', () => assert.throws(() => M.create(tiny(), [edge('A', 'B', 1)])));
test('Duplicate and reversed pairs rejected', () => { const e = edge('A', 'B', 1, '能走车'); assert.throws(() => M.create(tiny(), [e, e])); assert.throws(() => M.create(tiny(), [edge('B', 'A', 1, '能走车')])); });
test('Foreign key and self-loop rejected', () => { assert.throws(() => M.create(tiny(), [edge('A', 'D', 1, '能走车')])); assert.throws(() => M.create(tiny(), [edge('A', 'A', 1, '能走车')])); });
test('Water direction respected', () => { const m = M.create(tiny(), [edge('A', 'B', null, null, 7)]); assert.equal(m.route('A', 'B', 'water').distance, 7); assert.equal(m.route('B', 'A', 'water'), null); });
test('Different outbound and inbound lengths are preserved', () => { const m = M.create(tiny(), [edge('A', 'B', null, null, 7, 13)]); assert.equal(m.route('B', 'A', 'water').distance, 13); assert.equal(m.neighbors('B')[0].outbound, 13); assert.equal(m.neighbors('B')[0].inbound, 7); });
test('Land is bidirectional', () => { const m = M.create(tiny(), [edge('A', 'B', 2.75, '能走车')]); assert.equal(m.route('B', 'A', 'land').distance, 2.75); });
test('Shortest route uses intermediate counties, not direct or screen distance', () => { const m = M.create(tiny(), [edge('A', 'B', 2, '能走车'), edge('B', 'C', 3, '能走车'), edge('A', 'C', 10, '能走车')]); assert.deepEqual(m.route('A', 'C', 'land').ids, ['A', 'B', 'C']); assert.equal(m.route('A', 'C', 'land').distance, 5); });
test('Cart route excludes paths that cannot take carts', () => { const m = M.create(tiny(), [edge('A', 'B', 2, '能走车'), edge('B', 'C', 3, '能走车'), edge('A', 'C', 1, '不能走车')]); assert.equal(m.route('A', 'C', 'cart').distance, 5); assert.equal(m.route('A', 'C', 'land').distance, 1); });
test('Land and water never auto-transfer', () => { const m = M.create(tiny(), [edge('A', 'B', 2, '能走车'), edge('B', 'C', null, null, 3)]); assert.equal(m.route('A', 'C', 'land'), null); assert.equal(m.route('A', 'C', 'water'), null); });
test('No path returns null; same county returns zero path, not a zero edge', () => { const m = M.create(tiny(), []); assert.equal(m.route('A', 'C', 'cart'), null); assert.deepEqual(m.route('A', 'A', 'water'), { ids: ['A'], steps: [], distance: 0, mode: 'water' }); });
test('Unknown route nodes/modes rejected', () => { assert.throws(() => model.route('missing', counties[0]['县编号'], 'land')); assert.throws(() => model.route(counties[0]['县编号'], counties[0]['县编号'], 'mixed')); });
test('Modern reference names remain searchable', () => assert.ok(model.search('洛阳').some(c => c['县名'] === '洛邑')));
test('Filters preserve null country meaning', () => assert.ok(model.search('', '__none').every(c => c['开局行政归属']['所属国家'] === null)));
test('All resources and terrain filters use source values', () => { assert.ok(model.search('', '', '', '铜矿').every(c => c['自然资源'].includes('铜矿'))); assert.ok(model.search('', '', '山地').every(c => c['地形'] === '山地')); });
test('Projection roundtrip, including farthest corners', () => { for (const p of [[101.5, 24.5], [112.43, 34.67], [126, 43.2]]) { const q = M.unproject(M.project(p)); assert.ok(Math.abs(q[0] - p[0]) < 1e-8); assert.ok(Math.abs(q[1] - p[1]) < 1e-8); } });
test('Actual graph path weight equals the sum of original edge distances', () => { for (const mode of ['land', 'cart', 'water']) { const r = model.route(counties[0]['县编号'], counties[4]['县编号'], mode); if (r) assert.equal(r.distance, r.steps.reduce((n, s) => n + s.distance, 0)); } });
test('Model queries do not mutate the original two arrays', () => { const before = signature([counties, edges]); model.neighbors(counties[0]['县编号']); model.search('洛'); model.route(counties[0]['县编号'], counties[20]['县编号'], 'land'); assert.equal(signature([counties, edges]), before); });
