/* BC770 viewer: browser-only source loading, normal white land, no fabricated fields. */
'use strict';
(async()=>{
const $=id=>document.getElementById(id), node=(tag,value,cls)=>{const e=document.createElement(tag);if(value!=null)e.textContent=value;if(cls)e.className=cls;return e;};
const canvas=$('map'),ctx=canvas.getContext('2d'),hit=document.createElement('canvas').getContext('2d'),COS=.82;
const palette=['#cbded9','#dcd1dd','#dce1bd','#c7dce3','#e8d2bb','#d1d3e3','#d9dfcc','#e2d7be','#c9dedc','#ddd3ca','#d4e0c3','#cdd5e4'];
let source=null,original='',originalName='allhistory-770bc-china.json',records=[],byId=new Map(),fullBounds=[],scheduled=false,toastTimer,pointers=new Map(),gesture,moved=false;
const state={w:0,h:0,dpr:1,s:1,tx:0,ty:0,selected:null,mode:'joined',filter:'all',labels:true,unknown:true};
const mobile=()=>matchMedia('(max-width:680px)').matches,narrow=()=>matchMedia('(max-width:1000px)').matches;
const screen=(x,y)=>[state.tx+x*state.s*COS,state.ty-y*state.s],world=(x,y)=>[(x-state.tx)/(state.s*COS),(state.ty-y)/state.s];
function notify(s){clearTimeout(toastTimer);$('toast').textContent=s;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function store(mode,value){return new Promise((resolve,reject)=>{const request=indexedDB.open('zhou-bc770-source',1);let db,timer=setTimeout(()=>reject(Error('本地存储超时')),5000);request.onupgradeneeded=()=>request.result.createObjectStore('source');request.onerror=()=>{clearTimeout(timer);reject(request.error);};request.onblocked=()=>{clearTimeout(timer);reject(Error('本地存储被阻止'));};request.onsuccess=()=>{db=request.result;const tx=db.transaction('source',mode==='get'?'readonly':'readwrite'),os=tx.objectStore('source'),r=mode==='get'?os.get('current'):mode==='delete'?os.delete('current'):os.put(value,'current');let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>{clearTimeout(timer);db.close();resolve(result);};tx.onerror=()=>{clearTimeout(timer);db.close();reject(tx.error);};};});}
function paths(t){return t.rings.map(group=>{const p=new Path2D();for(const ring of group){p.moveTo(ring[0][0],-ring[0][1]);for(let i=1;i<ring.length;i++)p.lineTo(ring[i][0],-ring[i][1]);p.closePath();}return p;});}
function fit(b){if(!b.length)return;const [w,s,e,n]=b;state.s=Math.min((state.w-45)/(Math.max(e-w,.1)*COS),(state.h-45)/Math.max(n-s,.1));state.tx=state.w/2-(w+e)/2*state.s*COS;state.ty=state.h/2+(s+n)/2*state.s;schedule();}
function focus(){const r=byId.get(state.selected);if(!r)return;const [w,s,e,n]=r.bounds,dx=Math.max(e-w,.2),dy=Math.max(n-s,.2);fit([w-dx*.3,s-dy*.3,e+dx*.3,n+dy*.3]);}
function resize(){const b=$('stage').getBoundingClientRect(),ow=state.w,oh=state.h;state.w=b.width;state.h=b.height;state.dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(b.width*state.dpr);canvas.height=Math.round(b.height*state.dpr);if(!ow)fit([103,29,123,42]);else{state.tx+=(b.width-ow)/2;state.ty+=(b.height-oh)/2;schedule();}}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;draw();});}
function visible(r){const a=screen(r.bounds[0],r.bounds[3]),b=screen(r.bounds[2],r.bounds[1]);return a[0]<state.w&&b[0]>0&&a[1]<state.h&&b[1]>0;}
function maskFor(r){
 const key=[state.s,state.tx,state.ty,state.w,state.h,state.dpr].join('/');if(r.cache?.key===key)return r.cache;
 const p=screen(r.bounds[0],r.bounds[3]),q=screen(r.bounds[2],r.bounds[1]),left=Math.max(-5,Math.floor(p[0])-4),top=Math.max(-5,Math.floor(p[1])-4),right=Math.min(state.w+5,Math.ceil(q[0])+4),bottom=Math.min(state.h+5,Math.ceil(q[1])+4),w=Math.ceil((right-left)*state.dpr),h=Math.ceil((bottom-top)*state.dpr);
 if(w<1||h<1)return null;
 const a=document.createElement('canvas'),b=document.createElement('canvas');a.width=b.width=w;a.height=b.height=h;
 const ac=a.getContext('2d'),bc=b.getContext('2d');for(const c of [ac,bc]){c.setTransform(state.dpr*state.s*COS,0,0,state.dpr*state.s,(state.tx-left)*state.dpr,(state.ty-top)*state.dpr);c.fillStyle='white';}
 // Union per fragment first; intersection of the two fill interpretations second.
 // This is screen rendering only: never changes any source coordinate or OID.
 for(const p of r.paths){ac.fill(p,'nonzero');bc.fill(p,'evenodd');}
 ac.setTransform(1,0,0,1,0,0);ac.globalCompositeOperation='destination-in';ac.drawImage(b,0,0);ac.globalCompositeOperation='source-in';ac.fillStyle=r.name===null?'#ffffff':r.color;ac.fillRect(0,0,w,h);ac.globalCompositeOperation='source-over';
 const tint=color=>{const c=document.createElement('canvas');c.width=w;c.height=h;const cc=c.getContext('2d');cc.drawImage(a,0,0);cc.globalCompositeOperation='source-in';cc.fillStyle=color;cc.fillRect(0,0,w,h);return c;};r.cache={key,image:a,edge:tint('#90a595'),selectedEdge:tint('#295654'),left,top,width:w/state.dpr,height:h/state.dpr};return r.cache;
}
function draw(){
 if(!state.w||!state.h)return;ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.clearRect(0,0,state.w,state.h);ctx.fillStyle='white';ctx.fillRect(0,0,state.w,state.h);
 const nw=world(0,0),se=world(state.w,state.h),step=state.s>120?1:state.s>25?2:5;ctx.strokeStyle='#f1f4ee';ctx.lineWidth=.6;
 for(let x=Math.ceil(nw[0]/step)*step;x<se[0];x+=step){const [sx]=screen(x,0);ctx.beginPath();ctx.moveTo(sx,0);ctx.lineTo(sx,state.h);ctx.stroke();}for(let y=Math.ceil(se[1]/step)*step;y<nw[1];y+=step){const [,sy]=screen(0,y);ctx.beginPath();ctx.moveTo(0,sy);ctx.lineTo(state.w,sy);ctx.stroke();}
 const near=records.filter(visible);for(const unknown of [false,true])for(const r of near){if((r.name===null)!==unknown)continue;
  if(state.mode==='joined'){
   const c=maskFor(r);if(!c)continue;const selected=r.id===state.selected,size=selected?1.6:.55,edge=selected?c.selectedEdge:c.edge;if(!unknown||state.unknown)for(const [dx,dy]of [[size,0],[-size,0],[0,size],[0,-size]])ctx.drawImage(edge,c.left+dx,c.top+dy,c.width,c.height);ctx.drawImage(c.image,c.left,c.top,c.width,c.height);
  }else{ctx.save();ctx.setTransform(state.dpr*state.s*COS,0,0,state.dpr*state.s,state.tx*state.dpr,state.ty*state.dpr);ctx.fillStyle=unknown?'white':r.color;ctx.strokeStyle=r.id===state.selected?'#28534e':'#869d91';ctx.lineWidth=(r.id===state.selected?2.5:.65)/state.s;ctx.setLineDash(unknown?[3/state.s,3/state.s]:[]);for(const p of r.paths){if(state.mode!=='outline')ctx.fill(p,'nonzero');if(!unknown||state.unknown)ctx.stroke(p);}ctx.restore();}
 }
 if(state.labels){const occupied=[];for(const r of near.filter(r=>r.name!==null).sort((a,b)=>Number(b.id===state.selected)-Number(a.id===state.selected)||a.index-b.index)){
  if(!r.t.labelCoord)continue;const [x,y]=screen(...r.t.labelCoord);if(x<8||x>state.w-8||y<14||y>state.h-14)continue;const area=(r.bounds[2]-r.bounds[0])*(r.bounds[3]-r.bounds[1])*state.s**2*COS;if(area<380&&r.id!==state.selected)continue;const size=r.id===state.selected?16:area>8000?14:11;ctx.font=(r.id===state.selected?'650 ':'500 ')+size+'px system-ui';const w=ctx.measureText(r.name).width,rect=[x-w/2-4,y-size/2-3,x+w/2+4,y+size/2+3];if(occupied.some(a=>rect[0]<a[2]&&rect[2]>a[0]&&rect[1]<a[3]&&rect[3]>a[1])&&r.id!==state.selected)continue;occupied.push(rect);ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=3;ctx.strokeStyle='#ffffffef';ctx.fillStyle=r.id===state.selected?'#264e4a':'#3e5d51';ctx.strokeText(r.name,x,y);ctx.fillText(r.name,x,y);
 }}ctx.textAlign='left';ctx.textBaseline='alphabetic';
}
function list(){const q=$('search').value.trim().toLocaleLowerCase(),items=records.filter(r=>(state.filter!=='named'||r.name!==null)&&(state.filter!=='unknown'||r.name===null)&&(!q||String(r.name??'未命名区域').toLocaleLowerCase().includes(q)||r.id.includes(q)));$('matchCount').textContent=items.length+' / '+records.length+' 个区域';$('regionList').replaceChildren();for(const r of items){const b=node('button',null,'region'+(r.id===state.selected?' selected':''));b.dataset.oid=r.id;b.setAttribute('aria-pressed',String(r.id===state.selected));const sw=node('i',null,'swatch');sw.style.background=r.name===null?'white':r.color;const label=node('span');label.append(node('b',r.name??'未命名区域'),node('small',r.id));b.append(sw,label);b.onclick=()=>select(r.id,true,true);$('regionList').append(b);}if(!items.length)$('regionList').append(node('p','没有匹配的名称或编号。','empty'));}
function syncPanels(){const l=mobile()&&$('sidebar').classList.contains('open'),d=narrow()&&$('detailPanel').classList.contains('open');$('sidebar').inert=mobile()&&!l;$('detailPanel').inert=narrow()&&!d;$('shade').hidden=!(mobile()&&(l||d));}
function closePanels(){$('sidebar').classList.remove('open');$('detailPanel').classList.remove('open');syncPanels();}
function showDetail(){if(narrow())$('detailPanel').classList.add('open');if(mobile())$('sidebar').classList.remove('open');syncPanels();}
function save(name,raw){const url=URL.createObjectURL(new Blob([raw],{type:'application/json;charset=utf-8'})),a=node('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function dialog(title,children){$('dialogBody').replaceChildren(node('h2',title),...children);$('dialog').showModal();}
function fact(dl,k,v){const r=node('div');r.append(node('dt',k),node('dd',v));dl.append(r);}
function select(id,doFocus=false,open=false){const r=byId.get(id);if(!r)return;state.selected=id;const root=$('detail');root.replaceChildren(node('h2',r.name??'未命名区域'),node('div',r.id,'oid'),node('div',r.name===null?'正常白地 · 名称未提供':'来源名称 · 前770年','badge'));const dl=node('dl',null,'facts');fact(dl,'来源年份','BC770 / 前770年');fact(dl,'行政层级','来源未提供');fact(dl,'上级隶属','来源未提供');fact(dl,'导出片段组',r.t.rings.length.toLocaleString());fact(dl,'坐标点',r.points.toLocaleString());fact(dl,'标签坐标',r.t.labelCoord?r.t.labelCoord.map(x=>x.toFixed(4)).join(', '):'来源未提供');root.append(dl,node('p','标签点只用于文字定位，不当作都城、县治或行政中心。'),node('div',r.name===null?'有边界但名称为 null，保持白地；不借用现代地名、不猜测归属。':'使用你提供的前770年图层。白地保持为空；没有现代县界、模拟人口或虚构道路。','callout'));
 const actions=node('div',null,'detail-actions'),inspect=node('button','查看 JSON'),download=node('button','下载此区域'),share=node('button','复制地区链接','wide');inspect.onclick=()=>dialog('原始来源记录',[node('p','保留原始字段与全部 rings，没有附加未知属性。'),node('pre',JSON.stringify(r.t,null,2))]);download.onclick=()=>save('BC770-'+r.id.replace(':','-')+'.json',JSON.stringify(r.t,null,2));share.onclick=async()=>{const url='https://hxnfebzkjwbs.github.io/zhou-map/#region='+encodeURIComponent(r.id);try{await navigator.clipboard.writeText(url);notify('地区链接已复制；打开者需载入同一份来源数据。');}catch(_){dialog('地区链接',[node('p','在载入同一来源数据的浏览器中定位此地区。'),node('pre',url)]);}};actions.append(inspect,download,share);root.append(actions);const details=node('details');details.append(node('summary','边界与来源说明'),node('p','拼接显示在屏幕上合并同一编号的导出片段，并取非零与奇偶填充解释的共同部分；歧义位置保留空白。未改动源坐标，不宣称独立核实了历史疆界。'),node('p','源 areaDeg2 = '+r.t.areaDeg2+'，单位为平方度，不当作公顷面积或道路距离。'),node('p','来源没有国以下统一行政层级、人口、土地、资源和交通。这些信息未知，不填成0。'));root.append(details);try{const url=new URL(location.href);url.hash='region='+encodeURIComponent(id);history.replaceState(null,'',url);}catch(_){}if(doFocus)focus();else schedule();list();if(open)showDetail();}
function blank(lon,lat){state.selected=null;$('detail').replaceChildren(node('h2','此处保持留白'),node('div','正常未知状态 · 不是错误','badge'),node('p',lon.toFixed(5)+'°E / '+lat.toFixed(5)+'°N','oid'),node('div','此处没有当前图层可识别的来源区域。保持白地，不补边界、命名或划给邻国。','callout'),node('p','不据此推定无人居住、无主土地、未开发或水面。'));list();schedule();showDetail();}
function hits(lon,lat){return records.filter(r=>{const [w,s,e,n]=r.bounds;if(lon<w||lon>e||lat<s||lat>n)return false;const nz=r.paths.some(p=>hit.isPointInPath(p,lon,-lat,'nonzero'));return nz&&(state.mode!=='joined'||r.paths.some(p=>hit.isPointInPath(p,lon,-lat,'evenodd')));}).sort((a,b)=>Number(a.name!==null)-Number(b.name!==null)||a.t.areaDeg2-b.t.areaDeg2);}
function pick(lon,lat){const found=hits(lon,lat);if(!found.length){blank(lon,lat);return;}select(found[0].id,false,true);if(found.length>1){const box=node('div',null,'callout');box.append(node('p','此点有 '+found.length+' 个来源记录重叠；不推定上下级：'));for(const r of found){const b=node('button',r.name??'未命名');b.style.cssText='font-size:10px;padding:3px 6px;margin:3px';b.onclick=()=>select(r.id,false,true);box.append(b);}$('detail').append(box);}}
async function load(raw,name,remember){const result=ZhouData.validate(JSON.parse(raw));const next=result.source.territories.map((t,i)=>({t,id:t.oid,name:t.name,index:i,bounds:ZhouData.boundsOf(t),paths:paths(t),color:palette[([...t.oid].reduce((a,c)=>Math.imul(a,31)+c.charCodeAt(0),0)>>>0)%palette.length],points:t.rings.reduce((n,g)=>n+g.reduce((v,r)=>v+r.length,0),0)}));source=result.source;original=raw;originalName=name;records=next;byId=new Map(next.map(r=>[r.id,r]));fullBounds=result.bounds;state.filter='all';$('search').value='';document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b.dataset.filter==='all');b.setAttribute('aria-pressed',String(b.dataset.filter==='all'));});$('total').textContent=result.counts.total.toLocaleString();$('named').textContent=result.counts.named.toLocaleString();$('unknown').textContent=result.counts.unknown.toLocaleString();$('download').disabled=false;$('loader').hidden=true;fit([103,29,123,42]);const requested=new URLSearchParams(location.hash.slice(1)).get('region');select(byId.has(requested)?requested:(records.find(r=>r.name==='东周')||records[0]).id,byId.has(requested));draw();document.body.dataset.ready='true';document.body.dataset.version='0.4.1';window.__atlas={source,records,state,screen,world,fit,hits,pick,select,blank,counts:result.counts,whiteLandIsError:false};if(remember){try{await store('put',{raw,name});$('storageStatus').textContent='已保存在本机';}catch(_){$('storageStatus').textContent='仅本次有效';notify('本机缓存不可用；地图仍可正常使用。');}}}
function zoom(f,x=state.w/2,y=state.h/2){const ns=Math.max(3,Math.min(5000,state.s*f)),ratio=ns/state.s;state.tx=x+(state.tx-x)*ratio;state.ty=y+(state.ty-y)*ratio;state.s=ns;schedule();}
function pos(e){const b=canvas.getBoundingClientRect();return {x:e.clientX-b.left,y:e.clientY-b.top};}
function resetGesture(){const p=[...pointers.values()];gesture=p.length===1?{...p[0]}:p.length>1?{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2,d:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}:null;}
canvas.onpointerdown=e=>{pointers.set(e.pointerId,pos(e));canvas.setPointerCapture(e.pointerId);if(pointers.size===1)moved=false;else moved=true;resetGesture();};canvas.onpointermove=e=>{const p=pos(e),ll=world(p.x,p.y);$('coords').textContent=ll[0].toFixed(4)+'°E / '+ll[1].toFixed(4)+'°N';if(!pointers.has(e.pointerId))return;const before=gesture;pointers.set(e.pointerId,p);resetGesture();if(!before||!gesture)return;const dx=gesture.x-before.x,dy=gesture.y-before.y;if(Math.hypot(dx,dy)>1.5)moved=true;state.tx+=dx;state.ty+=dy;if(gesture.d&&before.d>0)zoom(gesture.d/before.d,gesture.x,gesture.y);schedule();};canvas.onpointerup=e=>{if(!moved&&pointers.size===1&&source){const p=pos(e);pick(...world(p.x,p.y));}pointers.delete(e.pointerId);resetGesture();};canvas.onpointercancel=e=>{pointers.delete(e.pointerId);moved=true;resetGesture();};canvas.addEventListener('wheel',e=>{e.preventDefault();const p=pos(e);zoom(Math.exp(-Math.max(-130,Math.min(130,e.deltaY))*.003),p.x,p.y);},{passive:false});canvas.ondblclick=e=>{const p=pos(e);zoom(1.7,p.x,p.y);};canvas.onkeydown=e=>{if(['+','=','-','Home','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(['+','='].includes(e.key))zoom(1.4);else if(e.key==='-')zoom(1/1.4);else if(e.key==='Home')fit([103,29,123,42]);else{state.tx+=e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0;state.ty+=e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0;schedule();}}};
$('search').oninput=list;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});list();});$('showLabels').onchange=e=>{state.labels=e.target.checked;schedule();};$('showUnknown').onchange=e=>{state.unknown=e.target.checked;schedule();};$('mode').onchange=e=>{state.mode=e.target.value;$('modeNote').textContent={joined:'同编号片段拼接，取两种填充解释的共同部分；歧义处留白。',original:'按非零规则绘制原始片段。分片接缝不是行政界。',outline:'只显示原始线环，不填色；此模式的白色不代表白地。'}[state.mode];schedule();};$('core').onclick=()=>fit([103,29,123,42]);$('full').onclick=()=>fit(fullBounds);$('zoomIn').onclick=()=>zoom(1.5);$('zoomOut').onclick=()=>zoom(1/1.5);$('focus').onclick=focus;$('home').onclick=e=>{e.preventDefault();fit([103,29,123,42]);};$('mobileList').onclick=()=>{$('sidebar').classList.toggle('open');$('detailPanel').classList.remove('open');syncPanels();};$('shade').onclick=closePanels;$('closeDetail').onclick=closePanels;$('closeDialog').onclick=()=>$('dialog').close();$('download').onclick=()=>{if(source)save(originalName,original);};
$('about').onclick=()=>{const reset=node('button','清除本机保存的地图');reset.onclick=async()=>{await store('delete');notify('已清除本机缓存；当前打开的地图不会被改动。');};dialog('前770年 · 数据说明',[node('p','本页使用全历史 BC770 导出，保留原始名称、OID和全部坐标，不读取旧版现代县界或六边形。'),node('h3','白地是正常未知状态'),node('p','有几何但名称为 null 的记录保留白色；没有来源覆盖的区域也不补面。两者都不代表无人、无主或水面。'),node('h3','来源有什么，就展示什么'),node('p','来源包含国家、地区、族群与文化名称，未提供统一行政层级、上级隶属、人口土地、古代治所与交通。不虚构这些字段；标签点不是首都，平方度不是公顷。'),node('h3','原始数据与屏幕拼接'),node('p','同一OID的片段在屏幕上合并，取非零和奇偶填充的共同部分，不确定的填充位置留白。原始JSON和坐标完全不变，可切换原始片段或线框查看。来源历史解释未独立考证。'),node('h3','导入与保存'),node('p','首次在线使用，选择 allhistory-770bc-china.json；也支持同年份GeoJSON。文件只由浏览器读取，成功后保存在本机供下次访问。不上传到服务器，不会同步到别的设备。离线完整版已内嵌数据。'),node('p','原上传没有附商业使用或再分发授权，本项目不授予第三方数据许可。旧版保存在仓库 archive/v0.3-modern 分支。'),reset]);};
async function importFile(file){if(!file)return;try{if(file.size>100*1024*1024)throw Error('文件超过100MB。');await load(await file.text(),file.name,true);notify('已载入前770年数据，白地和原始编号完整保留。');}catch(e){notify('导入失败：'+e.message);if(!source)$('loadMessage').textContent=e.message;}}
$('openFile').onclick=$('chooseSource').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>importFile(e.target.files[0]);document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();document.body.classList.add('drop-active');}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)document.body.classList.remove('drop-active');});document.addEventListener('drop',e=>{e.preventDefault();document.body.classList.remove('drop-active');importFile(e.dataTransfer.files[0]);});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels();if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('dialog').open){e.preventDefault();if(mobile()){$('sidebar').classList.add('open');syncPanels();}$('search').focus();}});window.addEventListener('resize',syncPanels);new ResizeObserver(resize).observe($('stage'));resize();syncPanels();
try{if($('embedded-source')){if(typeof DecompressionStream==='undefined')throw Error('此浏览器不支持离线解压；请使用新版浏览器或导入JSON。');const bytes=Uint8Array.from(atob($('embedded-source').textContent.trim()),c=>c.charCodeAt(0));const raw=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();await load(raw,'allhistory-770bc-china.json',false);$('storageStatus').textContent='完整离线数据';}else{const saved=await store('get').catch(()=>null);if(saved){await load(saved.raw,saved.name,false);$('storageStatus').textContent='本机保存的数据';}else{try{const r=await fetch('data/territories.json',{cache:'no-cache'});if(r.ok){await load(await r.text(),'allhistory-770bc-china.json',false);$('storageStatus').textContent='仓库数据';}else throw Error('未提供仓库数据');}catch(_){$('loadMessage').textContent='选择你已导出的历史地图文件。首次载入后会在本机记住，下次访问自动打开。';document.body.dataset.ready='awaiting-file';}}}}catch(e){$('loadMessage').textContent=e.message;document.body.dataset.ready='awaiting-file';}
})();
